apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-page
spec:
  replicas: 3

  selector:
    matchLabels:
      app: login-page

  template:
    metadata:
      labels:
        app: login-page

    spec:
      containers:
      - name: login-page
        image: vijayvw/test:latest
        ports:
        - containerPort: 80

        imagePullPolicy: Always
